### ISSUE TITLE
 
 ​[project] 
 ​title = dmengine 
  
 ​[bootstrap] 
 ​main_collection = /connect/connect.collectionc 
  
 ​[input] 
 ​game_binding = /connect/game.input_bindingc 
  
 ​[display] 
 ​width = 640 
 ​height = 1136 
  
 ​[render] 
 ​clear_color_red = 0.173 
 ​clear_color_green = 0.184 
 ​clear_color_blue = 0.204 
 ​clear_color_alpha = 0 
  
 ​[android] 
 ​package = com.defold.devapp 
  
 ​[osx] 
 ​bundle_identifier = com.defold.devapp 
  
 ​[ios] 
 ​bundle_identifier = com.defold.devapp 
 

### ISSUE THREAD

**Issue by gitUP779** [defold/dev-app#1]

**Comment by gitUP779** [comment]
> 

 
 ​[project] 
 ​title = dmengine 
  
 ​[bootstrap] 
 ​main_collection = /connect/connect.collectionc 
  
 ​[input] 
 ​game_binding = /connect/game.input_bindingc 
  
 ​[display] 
 ​width = 640 
 ​height = 1136 
  
 ​[render] 
 ​clear_color_red = 0.173 
 ​clear_color_green = 0.184 
 ​clear_color_blue = 0.204 
 ​clear_color_alpha = 0 
  
 ​[android] 
 ​package = com.defold.devapp 
  
 ​[osx] 
 ​bundle_identifier = com.defold.devapp 
  
 ​[ios] 
 ​bundle_identifier = com.defold.devapp

**Comment by britzl** [comment]
Spam
