### ISSUE TITLE
Link to outdated repository

### ISSUE THREAD

**Issue by Fossean1** [defold/dev-app#2]
On [https://defold.com/manuals/dev-app/](https://defold.com/manuals/dev-app/) I found a link to this repository, which is considered to be already obsolete 🙂

![image](https://github.com/defold/dev-app/assets/53948838/4b48e60e-2328-4355-bc5d-ea7128e91101)

**Comment by britzl** [comment]
Thanks. The link has been removed. The recommended way is to bundle a content-less build of your project, as described further down on the page.
